(()=>{'use strict';const $=id=>document.getElementById(id);
const zones=[['Dhaka · Bangladesh','Asia/Dhaka'],['Singapore','Asia/Singapore'],['Tokyo','Asia/Tokyo'],['Seoul','Asia/Seoul'],['Dubai','Asia/Dubai'],['London','Europe/London'],['Paris','Europe/Paris'],['New York','America/New_York'],['Los Angeles','America/Los_Angeles'],['Sydney','Australia/Sydney'],['UTC','UTC']];
const sourceData=[['01','Vehicle Movement','Mechanical energy associated with moving vehicles.','Distributed recovery'],['02','Braking / Deceleration','Controlled deceleration may create recovery opportunities subject to safety and vehicle-energy analysis.','Mobility'],['03','Elevation Change','Potential energy associated with movement through elevation differences.','Structures'],['04','Controlled Water Flow','Hydraulic recovery where measured head, discharge and downstream requirements permit.','Hydraulic'],['05','Vibration','Small-scale electromechanical recovery in suitable vibrating infrastructure.','Mechanical'],['06','Footstep / Human Movement','Small-scale recovery in high-footfall environments.','Supplementary'],['07','Airflow','Recovery from suitable airflow conditions where viable.','Aerodynamic'],['08','Solar Support','Solar can complement the broader node architecture.','PV support'],['09','Infrastructure Interaction','Other site-specific mechanical interactions discovered by measurement.','Site-specific']];
const techData=[['⚙️','Mechanical systems','Source → mechanism → conversion → local use'],['💧','Hydraulic systems','Flow / pressure → turbine or recovery unit → electrical output'],['🔌','Electromechanical systems','Motion → generator → power conditioning'],['〰️','Vibration systems','Oscillation → transducer → low-power electronics'],['🌀','Pressure / flow recovery','Pressure differential → controlled conversion → useful power'],['☀️','Photovoltaic support','Solar resource → PV conversion → storage / local load'],['🔗','Hybrid arrangements','Multiple suitable recovery layers coordinated by control'],['🧠','Control + SCADA','Sensors → PLC/RTU → historian → alarms → operator view']];
const modelData=[['Road Energy Node','Vehicle movement, braking zones, junctions, elevation and roadside infrastructure.','Safety-first'],['Bridge / Flyover','PV support, selective harvesting, local storage and monitoring.','Infrastructure layer'],['Sluice / Hydraulic Node','17-gate energy-absorption concept plus controlled-entry recovery stage.','Reference hydraulic model'],['Utility Infrastructure','Energy-recovery nodes attached to suitable distributed infrastructure.','Site-specific'],['Storage Node','Battery or other storage sized from actual smoothing/backup duty.','Electrical layer'],['Smart Monitoring','Power, flow, vibration, temperature, gate position and system status.','SCADA layer']];
function fillGrid(id,data,kind){const el=$(id);if(!el)return;el.innerHTML=data.map(r=>kind==='source'?`<div class="card tech"><div class="num">${r[0]}</div><h3>${r[1]}</h3><p>${r[2]}</p><span class="tag">${r[3]}</span></div>`:kind==='tech'?`<div class="card tech"><div class="icon">${r[0]}</div><h3>${r[1]}</h3><p>${r[2]}</p></div>`:`<div class="card tech"><div class="num">MODULE</div><h3>${r[0]}</h3><p>${r[1]}</p><span class="tag">${r[2]}</span></div>`).join('')}
fillGrid('sourceGrid',sourceData,'source');fillGrid('techGrid',techData,'tech');fillGrid('modelGrid',modelData,'model');
function fmt(zone,opts){return new Intl.DateTimeFormat('en-GB',Object.assign({timeZone:zone},opts)).format(new Date())}function clock(zone){return fmt(zone,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}function date(zone){return fmt(zone,{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}
const localZone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC',sel=$('zoneSelect');zones.forEach(([label,zone])=>{const o=document.createElement('option');o.value=zone;o.textContent=`${label} · ${zone}`;sel.appendChild(o)});try{const saved=localStorage.getItem('igers-zone');if(saved&&zones.some(z=>z[1]===saved))sel.value=saved}catch(_){ }
function tick(){$('bdClock').textContent=clock('Asia/Dhaka');$('bdDate').textContent=date('Asia/Dhaka');$('localClock').textContent=clock(localZone);$('localDate').textContent=date(localZone);$('localZone').textContent=localZone;$('worldClock').textContent=clock(sel.value);$('worldDate').textContent=date(sel.value);$('systemTime').textContent=clock(localZone);$('systemDate').textContent=fmt(localZone,{day:'2-digit',month:'short',year:'numeric'})}
sel.addEventListener('change',()=>{try{localStorage.setItem('igers-zone',sel.value)}catch(_){ }tick()});tick();setInterval(tick,1000);
const started=Date.now();setInterval(()=>{const s=Math.floor((Date.now()-started)/1000),h=String(Math.floor(s/3600)).padStart(2,'0'),m=String(Math.floor(s%3600/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');$('uptime').textContent=`${h}:${m}:${sec}`},1000);
const inputs={p:$('inPower'),e:$('inEff'),cf:$('inCF'),t:$('inTariff')};function calc(){const p=Math.max(0,Number(inputs.p.value)||0),eff=Math.max(0,Math.min(100,Number(inputs.e.value)||0))/100,cf=Math.max(0,Math.min(100,Number(inputs.cf.value)||0))/100,tariff=Math.max(0,Number(inputs.t.value)||0),net=p*eff,gwh=net*8760*cf/1e6,lakh=gwh*1e6*tariff/100000;$('effText').textContent=Math.round(eff*100)+'%';$('cfText').textContent=Math.round(cf*100)+'%';$('outPower').textContent=net.toFixed(net<10?1:0);$('outAnnual').textContent=gwh.toFixed(2);$('outValue').textContent=lakh.toFixed(2);$('effBar').style.width=(eff*100)+'%';$('cfBar').style.width=(cf*100)+'%'}Object.values(inputs).forEach(el=>el.addEventListener('input',calc));calc();
const theme=$('themeBtn');try{if(localStorage.getItem('igers-theme')==='light')document.documentElement.classList.add('light')}catch(_){ }function syncTheme(){theme.textContent=document.documentElement.classList.contains('light')?'☀':'☾'}theme.addEventListener('click',()=>{document.documentElement.classList.toggle('light');try{localStorage.setItem('igers-theme',document.documentElement.classList.contains('light')?'light':'dark')}catch(_){ }syncTheme()});syncTheme();})();
